apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
    - image: d0rka/post-service
      context: PostService
      buildpacks:
        trustBuilder: true
        builder: "paketobuildpacks/builder:base"
      sync:
        auto: true
    - image: d0rka/comment-service
      context: CommentService
      buildpacks:
        trustBuilder: true
        builder: "paketobuildpacks/builder:base"
      sync:
        auto: true