apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: comment-service-server
  template:
    metadata:
      labels:
        component: comment-service-server
    spec:
      containers:
        - name: comment-service
          image: d0rka/comment-service
          ports:
            - containerPort: 80
          env:
            - name: MSSQL-HOST
              value: mssql-cis
            - name: MSSQL-USER
              value: sa
            - name: MSSQL-PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql-password
                  key: SA_PASSWORD
            - name: DATABASE_DEVELOPMENT
              value: comment-service-db-development
            - name: DATABASE_TEST
              value: comment-service-db-test
            - name: DATABASE_PRODUCTION
              value: comment-service-db-production
---
apiVersion: v1
kind: Service
metadata:
  name: comment-service-cis
spec:
  type: ClusterIP
  selector:
    component: comment-service-server
  ports:
    - port: 80
      targetPort: 80
