apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: comment-service-server
  template:
    metadata:
      labels:
        component: comment-service-server
    spec:
      containers:
        - name: comment-service
          image: d0rka/comment-service
          ports:
            - containerPort: 80
          env:
            - name: POSTGRES_HOST
              value: postgresql
            - name: POSTGRES_PORT
              value: '5432'
            - name: POSTGRES_USERNAME
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DATABASE
              value: comments-db
---
apiVersion: v1
kind: Service
metadata:
  name: comment-service-cis
spec:
  type: ClusterIP
  selector:
    component: comment-service-server
  ports:
    - port: 80
      targetPort: 80
