apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: post-service-server
  template:
    metadata:
      labels:
        component: post-service-server
    spec:
      containers:
        - name: post-service
          image: d0rka/post-service
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_HOST
              value: postgresql
            - name: POSTGRES_PORT
              value: '5432'
            - name: POSTGRES_USERNAME
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DATABASE
              value: posts-db
---
apiVersion: v1
kind: Service
metadata:
  name: post-service-cis
spec:
  type: ClusterIP
  selector:
    component: post-service-server
  ports:
    - port: 8080
      targetPort: 8080
