apiVersion: batch/v1
kind: Job
metadata:
  name: db-drop-comments
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: db-drop-comments
          image: d0rka/post-service-migrations
          imagePullPolicy: Never
          args: ["drop=true"]
          env:
            - name: POSTGRES_HOST
              value: postgres-cis
            - name: POSTGRES_PORT
              value: '5432'
            - name: POSTGRES_USERNAME
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: postgres-password
            - name: POSTGRES_DATABASE
              value: comments-db
